/* tools/gen-book.js — 生成开局库数据 engine/data/book-lines.js
 * 用法： node gomoku/tools/gen-book.js  [maxPlies] [depth] [width]
 * 原理：对 26 种指定开局，用引擎浅搜（Negamax+αβ）逐层展开候选，产出真实开局线。
 * 设计依据：§12.3（生成方式之一：自对弈/分析）、§35.4
 */
'use strict';
const path = require('path');
const fs = require('fs');
const core = require('../engine/core.js');
const OP = require('../engine/data/openings.js');
const SEARCH = require('../engine/search.js');
const RU = require('../engine/rules.js');
const BOOK = require('../engine/book.js');

const { EMPTY, BLACK, WHITE, opp, idxOf, NN } = core;

const MAX_PLIES = parseInt(process.argv[2], 10) || 8;   // 生成到第几手（含开局 3 手）
const CFG = {
  rule: 'freestyle', lambda: 0.9,
  width: parseInt(process.argv[4], 10) || 6,
  depth: parseInt(process.argv[3], 10) || 3,            // 每步浅搜深度
  radius: 2,
};
const BRANCH = { 4: 3, 5: 2 };                          // 第 4 手取前 3，第 5 手取前 2，之后取第 1

function genOpening(op) {
  const board = new Int8Array(NN);
  let color = BLACK;
  for (const m of op.moves) { board[idxOf(m.x, m.y)] = color; color = opp(color); }
  const prefix = op.moves.map(m => [m.x, m.y]);
  const lines = [];

  (function rec(b, ply, col, w) {
    if (ply > MAX_PLIES) { lines.push({ moves: prefix.slice(), w: w }); return; }
    const k = BRANCH[ply] || 1;
    const top = SEARCH.bestMoves(b, col, CFG, k);
    if (!top.length) { lines.push({ moves: prefix.slice(), w: w }); return; }
    top.forEach(function (mv, rank) {
      b[mv.i] = col;
      if (RU.isWin(b, mv.x, mv.y, col)) { b[mv.i] = EMPTY; return; }   // 开局阶段出现五连则截断
      prefix.push([mv.x, mv.y]);
      rec(b, ply + 1, opp(col), w * Math.max(1, k - rank));
      prefix.pop();
      b[mv.i] = EMPTY;
    });
  })(board, 4, colorsAfterOpening(), 1);

  return lines.map(function (l) {
    return { ruleSet: 'freestyle', opening: op.name, moves: l.moves, weight: l.w, source: 'generated' };
  });
  function colorsAfterOpening() { return WHITE; }   // 开局 3 手（黑-白-黑）后轮到白
}

// —— 主流程 ——
const t0 = Date.now();
const entries = [];
for (const op of OP.OPENINGS) {
  const es = genOpening(op);
  for (const e of es) entries.push(e);
  process.stdout.write('  ' + op.name + ' → ' + es.length + ' 条\n');
}

// 校验（复用 book.validateLine）
const rejected = [];
for (const e of entries) { const err = BOOK.validateLine(e); if (err) rejected.push({ opening: e.opening, error: err }); }

const out = {
  version: 1,
  ruleSet: 'freestyle',
  source: 'generated by tools/gen-book.js',
  config: { maxPlies: MAX_PLIES, depth: CFG.depth, width: CFG.width, branch: BRANCH },
  generatedAt: new Date().toISOString(),
  count: entries.length,
  entries: entries,
};

// ★ v3.20：与 gen-book-real.js 输出**同形**（UMD + `entries` getter + `unpack()`），
//   这样两版数据可以互相替换而不需要改任何调用方（book.js 只读 unpack()/entries）。
fs.writeFileSync(outPath,
  '(function (root, factory) {\n' +
  "  if (typeof module !== 'undefined' && module.exports) module.exports = factory(entries);\n" +
  '  else { root.G = root.G || {}; root.G.bookLines = factory(entries); }\n' +
  '  function entries() { return ' + JSON.stringify(entries) + '; }\n' +
  "})(typeof globalThis !== 'undefined' ? globalThis : this, function (entries) {\n" +
  "  'use strict';\n" +
  '  var META = ' + JSON.stringify({ version: 2, ruleSet: 'freestyle', source: out.source, config: out.config, count: out.count }) + ';\n' +
  '  var _e = null;\n' +
  '  META.PACKED = null;\n' +
  '  function unpack() { return _e || (_e = entries()); }\n' +
  "  Object.defineProperty(META, 'entries', { get: unpack, enumerable: true });\n" +
  '  META.unpack = unpack;\n' +
  '  return META;\n' +
  '});\n', 'utf8');

console.log('\n生成 ' + entries.length + ' 条开局线，非法 ' + rejected.length + ' 条');
console.log('写入 ' + outPath + '  (' + (fs.statSync(outPath).size / 1024).toFixed(1) + ' KB)');
console.log('耗时 ' + ((Date.now() - t0) / 1000).toFixed(1) + ' s');
